eqfeed_callback({
  "type":"FeatureCollection",
  "features":[
{
      "type":"Feature",
      "properties":{
        "name":"test"
      },
      "geometry":{
        "type":"Point",
        "coordinates":[
          -64.191339, 
          -31.411388
        ]
      }
    },
    {
      "type":"Feature",
      "properties":{
        "name":"test"
      },
      "geometry":{
        "type":"Point",
        "coordinates":[
          -64.197579, 
          -31.417798
        ]
      }
    },
    {
      "type":"Feature",
      "properties":{
        "name":"test"
      },
      "geometry":{
        "type":"Point",
        "coordinates":[
          -64.189789, 
          -31.418798
        ]
      }
    },
    {
      "type":"Feature",
      "properties":{
        "name":"test"
      },
      "geometry":{
        "type":"Point",
        "coordinates":[
          -64.1908797, 
          -31.420809
        ]
      }
    },
    {
      "type":"Feature",
      "properties":{
        "name":"test"
      },
      "geometry":{
        "type":"Point",
        "coordinates":[
          -64.1923223, 
          -31.4154534
        ]
      }
    },
    {
      "type":"Feature",
      "properties":{
        "name":"test"
      },
      "geometry":{
        "type":"Point",
        "coordinates":[
          -64.190182370, 
          -31.4278685
        ]
      }
    },
    {
      "type":"Feature",
      "properties":{
        "name":"test"
      },
      "geometry":{
        "type":"Point",
        "coordinates":[
          -64.1897238912, 
          -31.42597897
        ]
      }
    }
  ]
});